// /*
//  * Copyright (C) 2015 John Leacox
//  *
//  * Licensed under the Apache License, Version 2.0 (the "License");
//  * you may not use this file except in compliance with the License.
//  * You may obtain a copy of the License at
//  *
//  * http://www.apache.org/licenses/LICENSE-2.0
//  *
//  * Unless required by applicable law or agreed to in writing, software
//  * distributed under the License is distributed on an "AS IS" BASIS,
//  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  * See the License for the specific language governing permissions and
//  * limitations under the License.
//  */
//
// Generated by Motif. Do Not Edit!
//
package com.leacox.motif.cases;

import com.leacox.motif.MatchesAny;
import com.leacox.motif.MatchesExact;
import com.leacox.motif.caseclass.Case1;
import com.leacox.motif.extract.DecomposableMatchBuilder0;
import com.leacox.motif.extract.DecomposableMatchBuilder1;
import com.leacox.motif.extract.DecomposableMatchBuilder2;
import com.leacox.motif.extract.DecomposableMatchBuilder3;
import com.leacox.motif.extract.matchers.ArgumentMatchers;
import com.leacox.motif.extract.matchers.Matcher;
import com.leacox.motif.extract.util.Lists;
import java.lang.Class;
import java.lang.Object;
import java.util.List;

/**
 * Motif cases for matching a {@link Case1}.
 */
public final class Case1Cases {
  private Case1Cases() {
  }

  /**
   * Matches a case class of one element.
   */
  public static <T extends Case1<A>, A> DecomposableMatchBuilder0<T> case1(Class<T> clazz, MatchesExact<A> a) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t));
    return new DecomposableMatchBuilder0<T>(matchers, new Case1FieldExtractor<>(clazz));
  }

  /**
   * Matches a case class of one element.
   *
   * <p>If matched, the {@code a} value is extracted.
   */
  public static <T extends Case1<A>, A> DecomposableMatchBuilder1<T, A> case1(Class<T> clazz, MatchesAny<A> a) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any());
    return new DecomposableMatchBuilder1<T, A>(matchers, 0, new Case1FieldExtractor<>(clazz));
  }

  /**
   * Matches a case class of one element.
   *
   * <p>If matched, the {@code a} value is decomposed to 0.
   */
  public static <T extends Case1<A>, A, EA extends A> DecomposableMatchBuilder0<T> case1(Class<T> clazz, DecomposableMatchBuilder0<EA> a) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any());
    return new DecomposableMatchBuilder1<T, EA>(matchers, 0, new Case1FieldExtractor<>(clazz)).decomposeFirst(a);
  }

  /**
   * Matches a case class of one element.
   *
   * <p>If matched, the {@code a} value is decomposed to 1.
   */
  public static <T extends Case1<A>, A, EA extends A, A1> DecomposableMatchBuilder1<T, A1> case1(Class<T> clazz, DecomposableMatchBuilder1<EA, A1> a) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any());
    return new DecomposableMatchBuilder1<T, EA>(matchers, 0, new Case1FieldExtractor<>(clazz)).decomposeFirst(a);
  }

  /**
   * Matches a case class of one element.
   *
   * <p>If matched, the {@code a} value is decomposed to 2.
   */
  public static <T extends Case1<A>, A, EA extends A, A1, A2> DecomposableMatchBuilder2<T, A1, A2> case1(Class<T> clazz, DecomposableMatchBuilder2<EA, A1, A2> a) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any());
    return new DecomposableMatchBuilder1<T, EA>(matchers, 0, new Case1FieldExtractor<>(clazz)).decomposeFirst(a);
  }

  /**
   * Matches a case class of one element.
   *
   * <p>If matched, the {@code a} value is decomposed to 3.
   */
  public static <T extends Case1<A>, A, EA extends A, A1, A2, A3> DecomposableMatchBuilder3<T, A1, A2, A3> case1(Class<T> clazz, DecomposableMatchBuilder3<EA, A1, A2, A3> a) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any());
    return new DecomposableMatchBuilder1<T, EA>(matchers, 0, new Case1FieldExtractor<>(clazz)).decomposeFirst(a);
  }
}
