// /*
//  * Copyright (C) 2015 John Leacox
//  *
//  * Licensed under the Apache License, Version 2.0 (the "License");
//  * you may not use this file except in compliance with the License.
//  * You may obtain a copy of the License at
//  *
//  * http://www.apache.org/licenses/LICENSE-2.0
//  *
//  * Unless required by applicable law or agreed to in writing, software
//  * distributed under the License is distributed on an "AS IS" BASIS,
//  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  * See the License for the specific language governing permissions and
//  * limitations under the License.
//  */
//
// Generated by Motif. Do Not Edit!
//
package com.leacox.motif.cases;

import com.leacox.motif.MatchesAny;
import com.leacox.motif.MatchesExact;
import com.leacox.motif.extract.DecomposableMatchBuilder0;
import com.leacox.motif.extract.DecomposableMatchBuilder1;
import com.leacox.motif.extract.DecomposableMatchBuilder2;
import com.leacox.motif.extract.DecomposableMatchBuilder3;
import com.leacox.motif.extract.matchers.ArgumentMatchers;
import com.leacox.motif.extract.matchers.Matcher;
import com.leacox.motif.extract.util.Lists;
import com.leacox.motif.tuple.Tuple2;
import com.leacox.motif.tuple.Tuple3;
import java.lang.Object;
import java.util.List;

/**
 * Motif cases for matching a {@link Tuple3}.
 */
public final class Tuple3Cases {
  private Tuple3Cases() {
  }

  /**
   * Matches a tuple of 2 elements.
   *
   */
  public static <A, B, C> DecomposableMatchBuilder0<Tuple3<A, B, C>> tuple3(MatchesExact<A> a, MatchesExact<B> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.eq(b.t), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder0<Tuple3<A, B, C>>(matchers, new Tuple3FieldExtractor<>());
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code c} value is extracted.
   *
   */
  public static <A, B, C> DecomposableMatchBuilder1<Tuple3<A, B, C>, C> tuple3(MatchesExact<A> a, MatchesExact<B> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, C>(matchers, 2, new Tuple3FieldExtractor<>());
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EC extends C> DecomposableMatchBuilder0<Tuple3<A, B, C>> tuple3(MatchesExact<A> a, MatchesExact<B> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, EC>(matchers, 2, new Tuple3FieldExtractor<>()).decomposeFirst(c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EC extends C, C1> DecomposableMatchBuilder1<Tuple3<A, B, C>, C1> tuple3(MatchesExact<A> a, MatchesExact<B> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, EC>(matchers, 2, new Tuple3FieldExtractor<>()).decomposeFirst(c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code c} value is decomposed to 2.
   *
   */
  public static <A, B, C, EC extends C, C1, C2> DecomposableMatchBuilder2<Tuple3<A, B, C>, C1, C2> tuple3(MatchesExact<A> a, MatchesExact<B> b, DecomposableMatchBuilder2<EC, C1, C2> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, EC>(matchers, 2, new Tuple3FieldExtractor<>()).decomposeFirst(c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code c} value is decomposed to 3.
   *
   */
  public static <A, B, C, EC extends C, C1, C2, C3> DecomposableMatchBuilder3<Tuple3<A, B, C>, C1, C2, C3> tuple3(MatchesExact<A> a, MatchesExact<B> b, DecomposableMatchBuilder3<EC, C1, C2, C3> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, EC>(matchers, 2, new Tuple3FieldExtractor<>()).decomposeFirst(c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is extracted.
   *
   */
  public static <A, B, C> DecomposableMatchBuilder1<Tuple3<A, B, C>, B> tuple3(MatchesExact<A> a, MatchesAny<B> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, B>(matchers, 1, new Tuple3FieldExtractor<>());
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is extracted and the {@code c} value is extracted.
   *
   */
  public static <A, B, C> DecomposableMatchBuilder2<Tuple3<A, B, C>, B, C> tuple3(MatchesExact<A> a, MatchesAny<B> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, B, C>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>());
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is extracted and the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EC extends C> DecomposableMatchBuilder1<Tuple3<A, B, C>, B> tuple3(MatchesExact<A> a, MatchesAny<B> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, B, EC>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeSecond(c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is extracted and the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EC extends C, C1> DecomposableMatchBuilder2<Tuple3<A, B, C>, B, C1> tuple3(MatchesExact<A> a, MatchesAny<B> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, B, EC>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeSecond(c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is extracted and the {@code c} value is decomposed to 2.
   *
   */
  public static <A, B, C, EC extends C, C1, C2> DecomposableMatchBuilder3<Tuple3<A, B, C>, B, C1, C2> tuple3(MatchesExact<A> a, MatchesAny<B> b, DecomposableMatchBuilder2<EC, C1, C2> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, B, EC>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeSecond(c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 0.
   *
   */
  public static <A, B, C, EB extends B> DecomposableMatchBuilder0<Tuple3<A, B, C>> tuple3(MatchesExact<A> a, DecomposableMatchBuilder0<EB> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, EB>(matchers, 1, new Tuple3FieldExtractor<>()).decomposeFirst(b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 0 and the {@code c} value is extracted.
   *
   */
  public static <A, B, C, EB extends B> DecomposableMatchBuilder1<Tuple3<A, B, C>, C> tuple3(MatchesExact<A> a, DecomposableMatchBuilder0<EB> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EB, C>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeFirst(b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 0 and the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EB extends B, EC extends C> DecomposableMatchBuilder0<Tuple3<A, B, C>> tuple3(MatchesExact<A> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EB, EC>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 0 and the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EB extends B, EC extends C, C1> DecomposableMatchBuilder1<Tuple3<A, B, C>, C1> tuple3(MatchesExact<A> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EB, EC>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 0 and the {@code c} value is decomposed to 2.
   *
   */
  public static <A, B, C, EB extends B, EC extends C, C1, C2> DecomposableMatchBuilder2<Tuple3<A, B, C>, C1, C2> tuple3(MatchesExact<A> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder2<EC, C1, C2> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EB, EC>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 0 and the {@code c} value is decomposed to 3.
   *
   */
  public static <A, B, C, EB extends B, EC extends C, C1, C2, C3> DecomposableMatchBuilder3<Tuple3<A, B, C>, C1, C2, C3> tuple3(MatchesExact<A> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder3<EC, C1, C2, C3> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EB, EC>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 1.
   *
   */
  public static <A, B, C, EB extends B, B1> DecomposableMatchBuilder1<Tuple3<A, B, C>, B1> tuple3(MatchesExact<A> a, DecomposableMatchBuilder1<EB, B1> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, EB>(matchers, 1, new Tuple3FieldExtractor<>()).decomposeFirst(b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 1 and the {@code c} value is extracted.
   *
   */
  public static <A, B, C, EB extends B, B1> DecomposableMatchBuilder2<Tuple3<A, B, C>, B1, C> tuple3(MatchesExact<A> a, DecomposableMatchBuilder1<EB, B1> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EB, C>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeFirst(b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 1 and the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EB extends B, B1, EC extends C> DecomposableMatchBuilder1<Tuple3<A, B, C>, B1> tuple3(MatchesExact<A> a, DecomposableMatchBuilder1<EB, B1> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EB, EC>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 1 and the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EB extends B, B1, EC extends C, C1> DecomposableMatchBuilder2<Tuple3<A, B, C>, B1, C1> tuple3(MatchesExact<A> a, DecomposableMatchBuilder1<EB, B1> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EB, EC>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 1 and the {@code c} value is decomposed to 2.
   *
   */
  public static <A, B, C, EB extends B, B1, EC extends C, C1, C2> DecomposableMatchBuilder3<Tuple3<A, B, C>, B1, C1, C2> tuple3(MatchesExact<A> a, DecomposableMatchBuilder1<EB, B1> b, DecomposableMatchBuilder2<EC, C1, C2> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EB, EC>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 2.
   *
   */
  public static <A, B, C, EB extends B, B1, B2> DecomposableMatchBuilder2<Tuple3<A, B, C>, B1, B2> tuple3(MatchesExact<A> a, DecomposableMatchBuilder2<EB, B1, B2> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, EB>(matchers, 1, new Tuple3FieldExtractor<>()).decomposeFirst(b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 2 and the {@code c} value is extracted.
   *
   */
  public static <A, B, C, EB extends B, B1, B2> DecomposableMatchBuilder3<Tuple3<A, B, C>, B1, B2, C> tuple3(MatchesExact<A> a, DecomposableMatchBuilder2<EB, B1, B2> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EB, C>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeFirst(b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 2 and the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EB extends B, B1, B2, EC extends C> DecomposableMatchBuilder2<Tuple3<A, B, C>, B1, B2> tuple3(MatchesExact<A> a, DecomposableMatchBuilder2<EB, B1, B2> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EB, EC>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 2 and the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EB extends B, B1, B2, EC extends C, C1> DecomposableMatchBuilder3<Tuple3<A, B, C>, B1, B2, C1> tuple3(MatchesExact<A> a, DecomposableMatchBuilder2<EB, B1, B2> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EB, EC>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 3.
   *
   */
  public static <A, B, C, EB extends B, B1, B2, B3> DecomposableMatchBuilder3<Tuple3<A, B, C>, B1, B2, B3> tuple3(MatchesExact<A> a, DecomposableMatchBuilder3<EB, B1, B2, B3> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, EB>(matchers, 1, new Tuple3FieldExtractor<>()).decomposeFirst(b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code b} value is decomposed to 3 and the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EB extends B, B1, B2, B3, EC extends C> DecomposableMatchBuilder3<Tuple3<A, B, C>, B1, B2, B3> tuple3(MatchesExact<A> a, DecomposableMatchBuilder3<EB, B1, B2, B3> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.eq(a.t), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EB, EC>(matchers, Tuple2.of(1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted.
   *
   */
  public static <A, B, C> DecomposableMatchBuilder1<Tuple3<A, B, C>, A> tuple3(MatchesAny<A> a, MatchesExact<B> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, A>(matchers, 0, new Tuple3FieldExtractor<>());
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code c} value is extracted.
   *
   */
  public static <A, B, C> DecomposableMatchBuilder2<Tuple3<A, B, C>, A, C> tuple3(MatchesAny<A> a, MatchesExact<B> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, A, C>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>());
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EC extends C> DecomposableMatchBuilder1<Tuple3<A, B, C>, A> tuple3(MatchesAny<A> a, MatchesExact<B> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, A, EC>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeSecond(c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EC extends C, C1> DecomposableMatchBuilder2<Tuple3<A, B, C>, A, C1> tuple3(MatchesAny<A> a, MatchesExact<B> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, A, EC>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeSecond(c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code c} value is decomposed to 2.
   *
   */
  public static <A, B, C, EC extends C, C1, C2> DecomposableMatchBuilder3<Tuple3<A, B, C>, A, C1, C2> tuple3(MatchesAny<A> a, MatchesExact<B> b, DecomposableMatchBuilder2<EC, C1, C2> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, A, EC>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeSecond(c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is extracted.
   *
   */
  public static <A, B, C> DecomposableMatchBuilder2<Tuple3<A, B, C>, A, B> tuple3(MatchesAny<A> a, MatchesAny<B> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, A, B>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>());
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is extracted and the {@code c} value
   * is extracted.
   *
   */
  public static <A, B, C> DecomposableMatchBuilder3<Tuple3<A, B, C>, A, B, C> tuple3(MatchesAny<A> a, MatchesAny<B> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, A, B, C>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>());
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is extracted and the {@code c} value
   * is decomposed to 0.
   *
   */
  public static <A, B, C, EC extends C> DecomposableMatchBuilder2<Tuple3<A, B, C>, A, B> tuple3(MatchesAny<A> a, MatchesAny<B> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, A, B, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeThird(c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is extracted and the {@code c} value
   * is decomposed to 1.
   *
   */
  public static <A, B, C, EC extends C, C1> DecomposableMatchBuilder3<Tuple3<A, B, C>, A, B, C1> tuple3(MatchesAny<A> a, MatchesAny<B> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, A, B, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeThird(c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is decomposed to 0.
   *
   */
  public static <A, B, C, EB extends B> DecomposableMatchBuilder1<Tuple3<A, B, C>, A> tuple3(MatchesAny<A> a, DecomposableMatchBuilder0<EB> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, A, EB>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeSecond(b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is decomposed to 0 and the {@code
   * c} value is extracted.
   *
   */
  public static <A, B, C, EB extends B> DecomposableMatchBuilder2<Tuple3<A, B, C>, A, C> tuple3(MatchesAny<A> a, DecomposableMatchBuilder0<EB> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, A, EB, C>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeSecond(b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is decomposed to 0 and the {@code
   * c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EB extends B, EC extends C> DecomposableMatchBuilder1<Tuple3<A, B, C>, A> tuple3(MatchesAny<A> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, A, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeSecondAndThird(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is decomposed to 0 and the {@code
   * c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EB extends B, EC extends C, C1> DecomposableMatchBuilder2<Tuple3<A, B, C>, A, C1> tuple3(MatchesAny<A> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, A, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeSecondAndThird(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is decomposed to 0 and the {@code
   * c} value is decomposed to 2.
   *
   */
  public static <A, B, C, EB extends B, EC extends C, C1, C2> DecomposableMatchBuilder3<Tuple3<A, B, C>, A, C1, C2> tuple3(MatchesAny<A> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder2<EC, C1, C2> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, A, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeSecondAndThird(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is decomposed to 1.
   *
   */
  public static <A, B, C, EB extends B, B1> DecomposableMatchBuilder2<Tuple3<A, B, C>, A, B1> tuple3(MatchesAny<A> a, DecomposableMatchBuilder1<EB, B1> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, A, EB>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeSecond(b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is decomposed to 1 and the {@code
   * c} value is extracted.
   *
   */
  public static <A, B, C, EB extends B, B1> DecomposableMatchBuilder3<Tuple3<A, B, C>, A, B1, C> tuple3(MatchesAny<A> a, DecomposableMatchBuilder1<EB, B1> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, A, EB, C>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeSecond(b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is decomposed to 1 and the {@code
   * c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EB extends B, B1, EC extends C> DecomposableMatchBuilder2<Tuple3<A, B, C>, A, B1> tuple3(MatchesAny<A> a, DecomposableMatchBuilder1<EB, B1> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, A, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeSecondAndThird(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is decomposed to 1 and the {@code
   * c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EB extends B, B1, EC extends C, C1> DecomposableMatchBuilder3<Tuple3<A, B, C>, A, B1, C1> tuple3(MatchesAny<A> a, DecomposableMatchBuilder1<EB, B1> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, A, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeSecondAndThird(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is decomposed to 2.
   *
   */
  public static <A, B, C, EB extends B, B1, B2> DecomposableMatchBuilder3<Tuple3<A, B, C>, A, B1, B2> tuple3(MatchesAny<A> a, DecomposableMatchBuilder2<EB, B1, B2> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, A, EB>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeSecond(b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} is extracted and the {@code b} value is decomposed to 2 and the {@code
   * c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EB extends B, B1, B2, EC extends C> DecomposableMatchBuilder3<Tuple3<A, B, C>, A, B1, B2> tuple3(MatchesAny<A> a, DecomposableMatchBuilder2<EB, B1, B2> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, A, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeSecondAndThird(b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A> DecomposableMatchBuilder0<Tuple3<A, B, C>> tuple3(DecomposableMatchBuilder0<EA> a, MatchesExact<B> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, EA>(matchers, 0, new Tuple3FieldExtractor<>()).decomposeFirst(a);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code c} value is extracted.
   *
   */
  public static <A, B, C, EA extends A> DecomposableMatchBuilder1<Tuple3<A, B, C>, C> tuple3(DecomposableMatchBuilder0<EA> a, MatchesExact<B> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, C>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeFirst(a);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, EC extends C> DecomposableMatchBuilder0<Tuple3<A, B, C>> tuple3(DecomposableMatchBuilder0<EA> a, MatchesExact<B> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EC>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, EC extends C, C1> DecomposableMatchBuilder1<Tuple3<A, B, C>, C1> tuple3(DecomposableMatchBuilder0<EA> a, MatchesExact<B> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EC>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code c} value is decomposed to 2.
   *
   */
  public static <A, B, C, EA extends A, EC extends C, C1, C2> DecomposableMatchBuilder2<Tuple3<A, B, C>, C1, C2> tuple3(DecomposableMatchBuilder0<EA> a, MatchesExact<B> b, DecomposableMatchBuilder2<EC, C1, C2> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EC>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code c} value is decomposed to 3.
   *
   */
  public static <A, B, C, EA extends A, EC extends C, C1, C2, C3> DecomposableMatchBuilder3<Tuple3<A, B, C>, C1, C2, C3> tuple3(DecomposableMatchBuilder0<EA> a, MatchesExact<B> b, DecomposableMatchBuilder3<EC, C1, C2, C3> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EC>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is extracted.
   *
   */
  public static <A, B, C, EA extends A> DecomposableMatchBuilder1<Tuple3<A, B, C>, B> tuple3(DecomposableMatchBuilder0<EA> a, MatchesAny<B> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, B>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeFirst(a);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is extracted and the {@code
   * c} value is extracted.
   *
   */
  public static <A, B, C, EA extends A> DecomposableMatchBuilder2<Tuple3<A, B, C>, B, C> tuple3(DecomposableMatchBuilder0<EA> a, MatchesAny<B> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, B, C>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirst(a);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is extracted and the {@code
   * c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, EC extends C> DecomposableMatchBuilder1<Tuple3<A, B, C>, B> tuple3(DecomposableMatchBuilder0<EA> a, MatchesAny<B> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, B, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndThird(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is extracted and the {@code
   * c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, EC extends C, C1> DecomposableMatchBuilder2<Tuple3<A, B, C>, B, C1> tuple3(DecomposableMatchBuilder0<EA> a, MatchesAny<B> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, B, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndThird(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is extracted and the {@code
   * c} value is decomposed to 2.
   *
   */
  public static <A, B, C, EA extends A, EC extends C, C1, C2> DecomposableMatchBuilder3<Tuple3<A, B, C>, B, C1, C2> tuple3(DecomposableMatchBuilder0<EA> a, MatchesAny<B> b, DecomposableMatchBuilder2<EC, C1, C2> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, B, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndThird(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, EB extends B> DecomposableMatchBuilder0<Tuple3<A, B, C>> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder0<EB> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EB>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 0 and
   * the {@code c} value is extracted.
   *
   */
  public static <A, B, C, EA extends A, EB extends B> DecomposableMatchBuilder1<Tuple3<A, B, C>, C> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder0<EB> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, C>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 0 and
   * the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, EC extends C> DecomposableMatchBuilder0<Tuple3<A, B, C>> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 0 and
   * the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, EC extends C, C1> DecomposableMatchBuilder1<Tuple3<A, B, C>, C1> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 0 and
   * the {@code c} value is decomposed to 2.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, EC extends C, C1, C2> DecomposableMatchBuilder2<Tuple3<A, B, C>, C1, C2> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder2<EC, C1, C2> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 0 and
   * the {@code c} value is decomposed to 3.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, EC extends C, C1, C2, C3> DecomposableMatchBuilder3<Tuple3<A, B, C>, C1, C2, C3> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder3<EC, C1, C2, C3> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, B1> DecomposableMatchBuilder1<Tuple3<A, B, C>, B1> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder1<EB, B1> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EB>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 1 and
   * the {@code c} value is extracted.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, B1> DecomposableMatchBuilder2<Tuple3<A, B, C>, B1, C> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder1<EB, B1> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, C>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 1 and
   * the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, B1, EC extends C> DecomposableMatchBuilder1<Tuple3<A, B, C>, B1> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder1<EB, B1> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 1 and
   * the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, B1, EC extends C, C1> DecomposableMatchBuilder2<Tuple3<A, B, C>, B1, C1> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder1<EB, B1> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 1 and
   * the {@code c} value is decomposed to 2.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, B1, EC extends C, C1, C2> DecomposableMatchBuilder3<Tuple3<A, B, C>, B1, C1, C2> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder1<EB, B1> b, DecomposableMatchBuilder2<EC, C1, C2> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 2.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, B1, B2> DecomposableMatchBuilder2<Tuple3<A, B, C>, B1, B2> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder2<EB, B1, B2> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EB>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 2 and
   * the {@code c} value is extracted.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, B1, B2> DecomposableMatchBuilder3<Tuple3<A, B, C>, B1, B2, C> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder2<EB, B1, B2> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, C>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 2 and
   * the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, B1, B2, EC extends C> DecomposableMatchBuilder2<Tuple3<A, B, C>, B1, B2> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder2<EB, B1, B2> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 2 and
   * the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, B1, B2, EC extends C, C1> DecomposableMatchBuilder3<Tuple3<A, B, C>, B1, B2, C1> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder2<EB, B1, B2> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 3.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, B1, B2, B3> DecomposableMatchBuilder3<Tuple3<A, B, C>, B1, B2, B3> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder3<EB, B1, B2, B3> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EB>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 0 and the {@code b} value is decomposed to 3 and
   * the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, EB extends B, B1, B2, B3, EC extends C> DecomposableMatchBuilder3<Tuple3<A, B, C>, B1, B2, B3> tuple3(DecomposableMatchBuilder0<EA> a, DecomposableMatchBuilder3<EB, B1, B2, B3> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, A1> DecomposableMatchBuilder1<Tuple3<A, B, C>, A1> tuple3(DecomposableMatchBuilder1<EA, A1> a, MatchesExact<B> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, EA>(matchers, 0, new Tuple3FieldExtractor<>()).decomposeFirst(a);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code c} value is extracted.
   *
   */
  public static <A, B, C, EA extends A, A1> DecomposableMatchBuilder2<Tuple3<A, B, C>, A1, C> tuple3(DecomposableMatchBuilder1<EA, A1> a, MatchesExact<B> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, C>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeFirst(a);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, EC extends C> DecomposableMatchBuilder1<Tuple3<A, B, C>, A1> tuple3(DecomposableMatchBuilder1<EA, A1> a, MatchesExact<B> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EC>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, A1, EC extends C, C1> DecomposableMatchBuilder2<Tuple3<A, B, C>, A1, C1> tuple3(DecomposableMatchBuilder1<EA, A1> a, MatchesExact<B> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EC>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code c} value is decomposed to 2.
   *
   */
  public static <A, B, C, EA extends A, A1, EC extends C, C1, C2> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, C1, C2> tuple3(DecomposableMatchBuilder1<EA, A1> a, MatchesExact<B> b, DecomposableMatchBuilder2<EC, C1, C2> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EC>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is extracted.
   *
   */
  public static <A, B, C, EA extends A, A1> DecomposableMatchBuilder2<Tuple3<A, B, C>, A1, B> tuple3(DecomposableMatchBuilder1<EA, A1> a, MatchesAny<B> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, B>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeFirst(a);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is extracted and the {@code
   * c} value is extracted.
   *
   */
  public static <A, B, C, EA extends A, A1> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, B, C> tuple3(DecomposableMatchBuilder1<EA, A1> a, MatchesAny<B> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, B, C>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirst(a);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is extracted and the {@code
   * c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, EC extends C> DecomposableMatchBuilder2<Tuple3<A, B, C>, A1, B> tuple3(DecomposableMatchBuilder1<EA, A1> a, MatchesAny<B> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, B, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndThird(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is extracted and the {@code
   * c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, A1, EC extends C, C1> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, B, C1> tuple3(DecomposableMatchBuilder1<EA, A1> a, MatchesAny<B> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, B, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndThird(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, EB extends B> DecomposableMatchBuilder1<Tuple3<A, B, C>, A1> tuple3(DecomposableMatchBuilder1<EA, A1> a, DecomposableMatchBuilder0<EB> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EB>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is decomposed to 0 and
   * the {@code c} value is extracted.
   *
   */
  public static <A, B, C, EA extends A, A1, EB extends B> DecomposableMatchBuilder2<Tuple3<A, B, C>, A1, C> tuple3(DecomposableMatchBuilder1<EA, A1> a, DecomposableMatchBuilder0<EB> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, C>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is decomposed to 0 and
   * the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, EB extends B, EC extends C> DecomposableMatchBuilder1<Tuple3<A, B, C>, A1> tuple3(DecomposableMatchBuilder1<EA, A1> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is decomposed to 0 and
   * the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, A1, EB extends B, EC extends C, C1> DecomposableMatchBuilder2<Tuple3<A, B, C>, A1, C1> tuple3(DecomposableMatchBuilder1<EA, A1> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is decomposed to 0 and
   * the {@code c} value is decomposed to 2.
   *
   */
  public static <A, B, C, EA extends A, A1, EB extends B, EC extends C, C1, C2> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, C1, C2> tuple3(DecomposableMatchBuilder1<EA, A1> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder2<EC, C1, C2> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, A1, EB extends B, B1> DecomposableMatchBuilder2<Tuple3<A, B, C>, A1, B1> tuple3(DecomposableMatchBuilder1<EA, A1> a, DecomposableMatchBuilder1<EB, B1> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EB>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is decomposed to 1 and
   * the {@code c} value is extracted.
   *
   */
  public static <A, B, C, EA extends A, A1, EB extends B, B1> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, B1, C> tuple3(DecomposableMatchBuilder1<EA, A1> a, DecomposableMatchBuilder1<EB, B1> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, C>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is decomposed to 1 and
   * the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, EB extends B, B1, EC extends C> DecomposableMatchBuilder2<Tuple3<A, B, C>, A1, B1> tuple3(DecomposableMatchBuilder1<EA, A1> a, DecomposableMatchBuilder1<EB, B1> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is decomposed to 1 and
   * the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, A1, EB extends B, B1, EC extends C, C1> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, B1, C1> tuple3(DecomposableMatchBuilder1<EA, A1> a, DecomposableMatchBuilder1<EB, B1> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is decomposed to 2.
   *
   */
  public static <A, B, C, EA extends A, A1, EB extends B, B1, B2> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, B1, B2> tuple3(DecomposableMatchBuilder1<EA, A1> a, DecomposableMatchBuilder2<EB, B1, B2> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EB>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 1 and the {@code b} value is decomposed to 2 and
   * the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, EB extends B, B1, B2, EC extends C> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, B1, B2> tuple3(DecomposableMatchBuilder1<EA, A1> a, DecomposableMatchBuilder2<EB, B1, B2> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 2.
   *
   */
  public static <A, B, C, EA extends A, A1, A2> DecomposableMatchBuilder2<Tuple3<A, B, C>, A1, A2> tuple3(DecomposableMatchBuilder2<EA, A1, A2> a, MatchesExact<B> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, EA>(matchers, 0, new Tuple3FieldExtractor<>()).decomposeFirst(a);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 2 and the {@code c} value is extracted.
   *
   */
  public static <A, B, C, EA extends A, A1, A2> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, A2, C> tuple3(DecomposableMatchBuilder2<EA, A1, A2> a, MatchesExact<B> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, C>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeFirst(a);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 2 and the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, A2, EC extends C> DecomposableMatchBuilder2<Tuple3<A, B, C>, A1, A2> tuple3(DecomposableMatchBuilder2<EA, A1, A2> a, MatchesExact<B> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EC>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 2 and the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, A1, A2, EC extends C, C1> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, A2, C1> tuple3(DecomposableMatchBuilder2<EA, A1, A2> a, MatchesExact<B> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EC>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 2 and the {@code b} value is extracted.
   *
   */
  public static <A, B, C, EA extends A, A1, A2> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, A2, B> tuple3(DecomposableMatchBuilder2<EA, A1, A2> a, MatchesAny<B> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, B>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeFirst(a);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 2 and the {@code b} value is extracted and the {@code
   * c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, A2, EC extends C> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, A2, B> tuple3(DecomposableMatchBuilder2<EA, A1, A2> a, MatchesAny<B> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, B, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndThird(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 2 and the {@code b} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, A2, EB extends B> DecomposableMatchBuilder2<Tuple3<A, B, C>, A1, A2> tuple3(DecomposableMatchBuilder2<EA, A1, A2> a, DecomposableMatchBuilder0<EB> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EB>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 2 and the {@code b} value is decomposed to 0 and
   * the {@code c} value is extracted.
   *
   */
  public static <A, B, C, EA extends A, A1, A2, EB extends B> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, A2, C> tuple3(DecomposableMatchBuilder2<EA, A1, A2> a, DecomposableMatchBuilder0<EB> b, MatchesAny<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, C>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 2 and the {@code b} value is decomposed to 0 and
   * the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, A2, EB extends B, EC extends C> DecomposableMatchBuilder2<Tuple3<A, B, C>, A1, A2> tuple3(DecomposableMatchBuilder2<EA, A1, A2> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 2 and the {@code b} value is decomposed to 0 and
   * the {@code c} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, A1, A2, EB extends B, EC extends C, C1> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, A2, C1> tuple3(DecomposableMatchBuilder2<EA, A1, A2> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder1<EC, C1> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 2 and the {@code b} value is decomposed to 1.
   *
   */
  public static <A, B, C, EA extends A, A1, A2, EB extends B, B1> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, A2, B1> tuple3(DecomposableMatchBuilder2<EA, A1, A2> a, DecomposableMatchBuilder1<EB, B1> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EB>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 2 and the {@code b} value is decomposed to 1 and
   * the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, A2, EB extends B, B1, EC extends C> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, A2, B1> tuple3(DecomposableMatchBuilder2<EA, A1, A2> a, DecomposableMatchBuilder1<EB, B1> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 3.
   *
   */
  public static <A, B, C, EA extends A, A1, A2, A3> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, A2, A3> tuple3(DecomposableMatchBuilder3<EA, A1, A2, A3> a, MatchesExact<B> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder1<Tuple3<A, B, C>, EA>(matchers, 0, new Tuple3FieldExtractor<>()).decomposeFirst(a);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 3 and the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, A2, A3, EC extends C> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, A2, A3> tuple3(DecomposableMatchBuilder3<EA, A1, A2, A3> a, MatchesExact<B> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.eq(b.t), ArgumentMatchers.any());
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EC>(matchers, Tuple2.of(0, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, c);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 3 and the {@code b} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, A2, A3, EB extends B> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, A2, A3> tuple3(DecomposableMatchBuilder3<EA, A1, A2, A3> a, DecomposableMatchBuilder0<EB> b, MatchesExact<C> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.eq(c.t));
    return new DecomposableMatchBuilder2<Tuple3<A, B, C>, EA, EB>(matchers, Tuple2.of(0, 1), new Tuple3FieldExtractor<>()).decomposeFirstAndSecond(a, b);
  }

  /**
   * Matches a tuple of 2 elements.
   *
   * <p>If matched, the {@code a} value is decomposed to 3 and the {@code b} value is decomposed to 0 and
   * the {@code c} value is decomposed to 0.
   *
   */
  public static <A, B, C, EA extends A, A1, A2, A3, EB extends B, EC extends C> DecomposableMatchBuilder3<Tuple3<A, B, C>, A1, A2, A3> tuple3(DecomposableMatchBuilder3<EA, A1, A2, A3> a, DecomposableMatchBuilder0<EB> b, DecomposableMatchBuilder0<EC> c) {
    List<Matcher<Object>> matchers = Lists.of(ArgumentMatchers.any(), ArgumentMatchers.any(), ArgumentMatchers.any());
    return new DecomposableMatchBuilder3<Tuple3<A, B, C>, EA, EB, EC>(matchers, Tuple3.of(0, 1, 2), new Tuple3FieldExtractor<>()).decomposeFirstAndSecondAndThird(a, b, c);
  }
}
